import type { AdminEnquiry } from "@/types/admin";

/** Development-only enquiries for the Phase 4 console. They are never persisted. */
export const mockEnquiries = [
  {
    id: "enq-2026-0917-01",
    submittedAt: "2026-09-17T09:40:00.000Z",
    status: "new",
    contactPerson: "R. Mehta",
    companyName: "Mehta Process Works",
    phone: "+91 98XXX 12044",
    email: "procurement@example.in",
    coalRequirement: "Steam coal for industrial boiler",
    gradeGcv: "GCV discussion requested",
    size: "To be discussed",
    quantity: "250",
    unit: "Tonnes",
    deliveryCity: "Nashik",
    state: "Maharashtra",
    timeline: "Within two weeks",
    message: "Please call before sending a commercial discussion.",
    notes: [],
  },
  {
    id: "enq-2026-0916-02",
    submittedAt: "2026-09-16T12:15:00.000Z",
    status: "contacted",
    contactPerson: "S. Iyer",
    companyName: "Deccan Chemicals",
    phone: "+91 97XXX 51820",
    email: "operations@example.in",
    whatsapp: "+91 97XXX 51820",
    coalRequirement: "Requirement-based sourcing",
    gradeGcv: "GCV to be confirmed",
    quantity: "1,200",
    unit: "Tonnes",
    deliveryCity: "Hyderabad",
    state: "Telangana",
    pincode: "5000XX",
    timeline: "October requirement",
    notes: [{ id: "note-01", createdAt: "2026-09-17T07:30:00.000Z", author: "Star Energies", text: "Called customer. Asked for GCV confirmation and delivery schedule." }],
  },
  {
    id: "enq-2026-0915-03",
    submittedAt: "2026-09-15T08:05:00.000Z",
    status: "quoted",
    contactPerson: "A. Shah",
    companyName: "Gujarat Brick & Lime",
    phone: "+91 99XXX 86412",
    email: "purchase@example.in",
    coalRequirement: "Coal for brick kiln application",
    size: "To be discussed",
    quantity: "500",
    unit: "Tonnes",
    deliveryCity: "Vadodara",
    state: "Gujarat",
    timeline: "This month",
    notes: [{ id: "note-02", createdAt: "2026-09-16T11:10:00.000Z", author: "Star Energies", text: "Commercial discussion shared for the requested route." }],
  },
  {
    id: "enq-2026-0912-04",
    submittedAt: "2026-09-12T10:20:00.000Z",
    status: "closed",
    contactPerson: "P. Kumar",
    companyName: "Eastern Manufacturing Co.",
    phone: "+91 96XXX 44019",
    email: "fuel@example.in",
    coalRequirement: "WCL coal discussion",
    quantity: "100",
    unit: "Tonnes",
    deliveryCity: "Visakhapatnam",
    state: "Andhra Pradesh",
    notes: [],
  },
] satisfies AdminEnquiry[];
