import type { Capability } from "@/types/content";

export const capabilities = [
  {
    id: "requirement-led-sourcing",
    slug: "requirement-led-sourcing",
    title: "Sourcing",
    shortDescription: "Requirement-led evaluation across available WCL, auction, e-auction, trader and supplier routes.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 1,
  },
  {
    id: "specification-discussion",
    slug: "specification-discussion",
    title: "Specification",
    shortDescription: "Discussion can begin with grade, GCV, size, application and the material information you have.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 2,
  },
  {
    id: "volume-flexibility",
    slug: "volume-flexibility",
    title: "Volume",
    shortDescription: "Requirements may range from approximately 100 tonnes to several thousand tonnes, subject to feasibility.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 3,
  },
  {
    id: "quality-information",
    slug: "quality-information",
    title: "Quality Information",
    shortDescription: "Quality or laboratory information can be considered where required and available for the material.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 4,
  },
  {
    id: "commercial-flexibility",
    slug: "commercial-flexibility",
    title: "Commercial Terms",
    shortDescription: "Advance or credit arrangements may be discussed depending on the transaction and commercial assessment.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 5,
  },
  {
    id: "third-party-transport-coordination",
    slug: "third-party-transport-coordination",
    title: "Transport Coordination",
    shortDescription: "Third-party transportation can be coordinated where required; Star Energies does not operate its own fleet.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 6,
  },
  {
    id: "direct-customer-communication",
    slug: "direct-customer-communication",
    title: "Direct Customer Communication",
    shortDescription: "A direct discussion helps establish the actual requirement and suitable next steps.",
    featured: false,
    active: true,
    status: "published",
    displayOrder: 7,
  },
] satisfies Capability[];
