import type { Industry } from "@/types/content";

export const industries = [
  {
    id: "manufacturing",
    slug: "manufacturing",
    name: "Manufacturing",
    shortDescription: "For manufacturing operations with coal requirements shaped by process, handling and destination.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 1,
  },
  {
    id: "chemical-industries",
    slug: "chemical-industries",
    name: "Chemical Industries",
    shortDescription: "For chemical-industry buyers assessing coal against the needs of a specific operation.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 2,
  },
  {
    id: "power",
    slug: "power",
    name: "Power",
    shortDescription: "For power-related industrial requirements considered against the material brief and commercial context.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 3,
  },
  {
    id: "industrial-boilers",
    slug: "industrial-boilers",
    name: "Industrial Boilers",
    shortDescription: "For boiler applications where the customer’s operating requirement guides the conversation.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 4,
  },
  {
    id: "brick-kilns",
    slug: "brick-kilns",
    name: "Brick Kilns",
    shortDescription: "For kiln operators discussing sourcing around their material requirement and delivery location.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 5,
  },
  {
    id: "other-industrial-users",
    slug: "other-industrial-users",
    name: "Other Industrial Users",
    shortDescription: "For industrial coal users whose application does not sit neatly inside a standard category.",
    featured: false,
    active: true,
    status: "published",
    displayOrder: 6,
  },
] satisfies Industry[];
