import type { Product } from "@/types/content";

/** Source categories, never ecommerce inventory. Public prices and stock counts are intentionally absent. */
export const products = [
  {
    id: "wcl-coal",
    slug: "wcl-coal",
    name: "WCL Coal",
    shortDescription: "Material sourced through available WCL channels, aligned to requirement and commercial feasibility.",
    sourceType: "WCL channels",
    availabilityNote: "Material availability and suitability are considered at the time of enquiry.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 1,
    consideredAgainst: "GRADE / DESTINATION",
  },
  {
    id: "auction-e-auction-coal",
    slug: "auction-e-auction-coal",
    name: "Auction / E-auction Coal",
    shortDescription: "Auction-led opportunities evaluated against the grade, quantity and destination you need.",
    sourceType: "Auction and e-auction",
    availabilityNote: "Material availability and suitability are considered at the time of enquiry.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 2,
    consideredAgainst: "AVAILABILITY / COMMERCIALS",
  },
  {
    id: "steam-coal",
    slug: "steam-coal",
    name: "Steam Coal",
    shortDescription: "Industrial steam-coal requirements considered with the operating context in view.",
    sourceType: "Requirement-led sourcing",
    availabilityNote: "Material availability and suitability are considered at the time of enquiry.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 3,
    consideredAgainst: "APPLICATION / SIZE",
  },
  {
    id: "requirement-based-sourcing",
    slug: "requirement-based-sourcing",
    name: "Requirement-Based Sourcing",
    shortDescription: "A sourcing approach shaped around your brief—not a fixed public catalogue.",
    sourceType: "Market suppliers and sourcing routes",
    availabilityNote: "Material availability and suitability are considered at the time of enquiry.",
    featured: true,
    active: true,
    status: "published",
    displayOrder: 4,
    consideredAgainst: "YOUR FULL BRIEF",
  },
] satisfies Product[];
